### ISSUE TITLE
in __init__.py line 208 on raise InvalidParamsError 

### ISSUE THREAD

**Issue by estin** [samuraisam/django-json-rpc#54]
in line https://github.com/samuraisam/django-json-rpc/blob/master/jsonrpc/__init__.py#L208

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jsonrpc/site.py", line 160, in response_dict
    R = apply_version[version](method, request, D['params'])
  File "/usr/local/lib/python2.7/dist-packages/jsonrpc/site.py", line 123, in <lambda>
    apply_version = {'2.0': lambda f, r, p: f(r, **encode_kw(p)) if type(p) is dict else f(r, *p),
  File "/usr/local/lib/python2.7/dist-packages/jsonrpc/__init__.py", line 208, in _func
    '[%s] or {%s} arguments', authentication_arguments)
TypeError: __init__() takes at most 2 arguments (3 given)
```

must be string formating by %

**Comment by bartmika** [comment]
+1

**Comment by samuraisam** [comment]
Accepting pull requests
